version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: dev
  ignore:
  - dependency-name: phpstan/phpstan
    versions:
    - 0.12.70
    - 0.12.71
    - 0.12.73
    - 0.12.74
    - 0.12.75
    - 0.12.76
    - 0.12.77
    - 0.12.78
    - 0.12.79
    - 0.12.80
    - 0.12.81
    - 0.12.82
    - 0.12.83
    - 0.12.84
  - dependency-name: phpunit/phpunit
    versions:
    - 8.5.14
